caFilePath: "${HOME}/.strap/okta/cacerts/Okta-Root-CA.pem"

enableStrictSsl: true

npmRegistryServer: "https://artifacts.aue1e.internal/artifactory/api/npm/npm-okta-master"
npmAuditRegistry: "https://artifacts.aue1e.internal/artifactory/api/npm/npm-okta-master"

npmScopes:
  okta:
    npmRegistryServer: "${OKTA_NPM_REGISTRY_SERVER-https://artifacts.aue1e.internal/artifactory/api/npm/npm-okta-all}"
    npmPublishRegistry: "https://artifacts.aue1e.internal/artifactory/api/npm/npm-topic"
