apiVersion: v1alpha
kind: testcafe
showConsoleLog: false
npm:
  packages:
    "@testcafe-community/axe": "^3.5.0"
    "axe-core": "^4.6.3"
sauce:
  region: us-west-1
  concurrency: 1
  sauceignore: .sauceignore
  tunnel: 
    name: OktaSignInWidget_testcafe_firefox
suites:
- name: testcafe - windows 11 - firefox
  browserName: firefox
  src:
    - 'test/testcafe/spec/IdentifyRecovery_spec.js'
    # - 'test/testcafe/spec/BYOL_spec.js'
    # - 'test/testcafe/spec/ChallengePIV_spec.js'
  platformName: Windows 11
  mode: sauce
  clientScripts: 
    - 'node_modules/axe-core/axe.min.js'
- name: testcafe - windows 10 - IE
  browserName: internet explorer
  browserVersion: latest
  src:
    - 'test/testcafe/spec/IdentifyRecovery_spec.js'
    # - 'test/testcafe/spec/BYOL_spec.js'
    # - 'test/testcafe/spec/ChallengePIV_spec.js'
  platformName: Windows 10
  mode: sauce
  clientScripts: 
    - 'node_modules/axe-core/axe.min.js'
testcafe:
  version: 1.20.0
rootDir: .
artifacts:
  download:
    match:
    - '*'
    when: fail
    directory: ./artifacts
